# Generated by Django 5.1.5 on 2025-05-01 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_user_code_sent_at_user_email_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code_sent_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
