# Generated by Django 5.1.6 on 2025-03-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='biodegradability',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='carbon_footprint',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='durability',
            field=models.CharField(default='0 months', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_efficiency',
            field=models.CharField(choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='material_sourcing',
            field=models.CharField(choices=[('good', 'Good'), ('better', 'Better'), ('best', 'Best')], default='good', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='recyclability',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='water_usage',
            field=models.CharField(choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], default='low', max_length=10),
        ),
    ]
