# Generated by Django 5.1.6 on 2025-03-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_biodegradability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='biodegradability',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carbon_footprint',
        ),
        migrations.RemoveField(
            model_name='product',
            name='recyclability',
        ),
        migrations.AddField(
            model_name='product',
            name='biodegradability_level',
            field=models.IntegerField(choices=[(0, 'Low (0-33)'), (1, 'Moderate (34-66)'), (2, 'High (67-100)')], default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='carbon_footprint_level',
            field=models.IntegerField(choices=[(0, 'Low (0-33)'), (1, 'Moderate (34-66)'), (2, 'High (67-100)')], default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='recyclability_level',
            field=models.IntegerField(choices=[(0, 'Low (0-33)'), (1, 'Moderate (34-66)'), (2, 'High (67-100)')], default=0),
        ),
    ]
