# Generated by Django 5.1.7 on 2025-03-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, default='1.00', max_digits=99999999999, null=True),
        ),
    ]
