# Generated by Django 5.1.7 on 2025-03-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_variant_selection_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['sku']},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
    ]
