# Generated by Django 5.1.7 on 2025-03-22 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.AlterUniqueTogether(
            name='productoption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant_selection',
        ),
        migrations.AlterField(
            model_name='product_images',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
        migrations.DeleteModel(
            name='EcoAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.DeleteModel(
            name='ProductOption',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
