# Generated by Django 5.1.7 on 2025-03-23 07:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_vendor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contact',
            field=models.CharField(default='91000000000', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid numeric contact number.', regex='^\\d+$')]),
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.product')),
            ],
        ),
    ]
