# Generated by Django 5.1.7 on 2025-03-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_vendor_contact_productoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='warrenty_period',
            new_name='warranty_period',
        ),
    ]
