# Generated by Django 5.1.7 on 2025-03-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_warrenty_period_vendor_warranty_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='option_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
