# Generated by Django 5.1.7 on 2025-03-30 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_product_reivew_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('process', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='process', max_length=30),
        ),
        # migrations.AlterUniqueTogether(
        #     name='product_reivew',
        #     unique_together={('product', 'user')},
        # ),
    ]
