# Generated by Django 5.1.7 on 2025-03-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product_reivew',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('process', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=30),
        ),
    ]
