# Generated by Django 5.1.7 on 2025-03-30 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_product_reivew_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_reivew',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
    ]
