# Generated by Django 5.1.5 on 2025-04-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_product_reivew_product'),
    ]

    operations = [
    ]
