# Generated by Django 5.1.5 on 2025-04-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_address_status_to_is_default'),
    ]

    operations = [
    ]
