# Generated by Django 5.1.5 on 2025-04-30 13:22

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.user_directory_path)),
                ('cert_no', models.CharField(max_length=100)),
                ('issued_on', models.DateField()),
                ('expires_on', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.vendor')),
            ],
            options={
                'verbose_name_plural': 'Certificates',
            },
        ),
    ]
