# Generated by Django 5.1.5 on 2025-04-30 13:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(upload_to=core.models.cert_directory_path),
        ),
    ]
